version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - pip install aws-sam-cli
  build:
    commands:
      - sam build --template-file infra/ClassifierApi.yaml
      - sam package --s3-bucket $ARTIFACTS_BUCKET --output-template-file packaged-template.yaml
artifacts:
  files:
    - packaged-template.yaml