AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI4NG Classifier Lambda API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: dotnet8

  Api:
    Name: AI4NG-dev
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"

Resources:

  # API Gateway (HTTP API)
  AI4NGHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: AI4NG-dev
      StageName: dev

  # Explicit Authorizer resource
  AI4NGCognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref AI4NGHttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - 517s6c84jo5i3lqste5idb0o4c
        Issuer: https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_EaNz6cSp0
      Name: AI4NGCognitoAuthorizer

  # Lambda Function
  ClassifierApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: AI4NGClassifierLambda::AI4NGClassifierLambda.LambdaEntryPoint::FunctionHandlerAsync
      CodeUri: ../src/AI4NGClassifierLambda
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaDynamoDBExecutionRole
      Events:
        GetClassifiers:
          Type: HttpApi
          Properties:
            Path: /api/classifiers
            Method: GET
            ApiId: !Ref AI4NGHttpApi
            Auth:
              Authorizer: !Ref AI4NGCognitoAuthorizer
        GetClassifierById:
          Type: HttpApi
          Properties:
            Path: /api/classifiers/{classifierId}
            Method: GET
            ApiId: !Ref AI4NGHttpApi
            Auth:
              Authorizer: !Ref AI4NGCognitoAuthorizer
        GetGraphsForClassifier:
          Type: HttpApi
          Properties:
            Path: /api/classifiers/{classifierId}/graphs
            Method: GET
            ApiId: !Ref AI4NGHttpApi
            Auth:
              Authorizer: !Ref AI4NGCognitoAuthorizer
        GetGraphByName:
          Type: HttpApi
          Properties:
            Path: /api/classifiers/{classifierId}/graphs/{graphName}
            Method: GET
            ApiId: !Ref AI4NGHttpApi
            Auth:
              Authorizer: !Ref AI4NGCognitoAuthorizer
      Environment:
        Variables:
          TABLE_NAME: classifiers

  # DynamoDB Table
  ClassifiersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: classifiers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${AI4NGHttpApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  SharedApiId:
    Value: !Ref AI4NGHttpApi
    Export:
      Name: SharedApiId
  SharedApiAuthorizerId:
    Value: !Ref AI4NGCognitoAuthorizer
    Export:
      Name: SharedApiAuthorizerId
