name: Generate and Publish Swagger

on:
  push:
    branches: [main]
    paths:
      - 'src/AI4NGClassifierLambda/**'
      - 'tools/DocsGenerator/**'
      - '.github/workflows/publish-swagger.yaml'
jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Lambda project
        run: dotnet build src/AI4NGClassifierLambda/AI4NGClassifierLambda.csproj --configuration Release

      - name: Build and run DocsGenerator
        run: |
          dotnet build tools/DocsGenerator/DocsGenerator.csproj --configuration Release
          dotnet run --project tools/DocsGenerator/DocsGenerator.csproj

      - name: Clone API Docs Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.DOCS_REPO_PAT }}@github.com/hss70/AI4NGApiDoc.git
          cp docs/swagger.yaml AI4NGApiDoc/apis/Classifiers.yaml
          cd AI4NGApiDoc
          git add apis/Classifiers.yaml
          git commit -m "Update classifier swagger from main"
          git push
