name: Generate and Publish Swagger

on:
  push:
    branches: [main]

jobs:
  generate-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: dotnet build src/AI4NGClassifierLambda/AI4NGClassifierLambda.csproj --configuration Release

      - name: Generate Swagger JSON
        run: |
          dotnet tool install --global Swashbuckle.AspNetCore.Cli
          dotnet swagger tofile \
            --output classifier.yaml \
            src/AI4NGClassifierLambda/bin/Release/net8.0/AI4NGClassifierLambda.dll \
            v1

      - name: Clone API Docs Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone https://x-access-token:${{ secrets.DOCS_REPO_PAT }}@github.com/hss70/AI4NGApiDoc.git
          cp swagger.yaml AI4NGApiDoc/apis/Classifiers.yaml
          cd AI4NGApiDoc
          git add .
          git commit -m "Update classifier swagger from main"
          git push